apiVersion: v1
kind: Namespace
metadata:
  name:  devops

---

apiVersion: v1
data:
  jwt.jks: MIIKZgIBAzCCChAGCSqGSIb3DQEHAaCCCgEEggn9MIIJ+TCCBbAGCSqGSIb3DQEHAaCCBaEEggWdMIIFmTCCBZUGCyqGSIb3DQEMCgECoIIFQDCCBTwwZgYJKoZIhvcNAQUNMFkwOAYJKoZIhvcNAQUMMCsEFJ1UbIV8Lonr27g7hqnUez0JaDJOAgInEAIBIDAMBggqhkiG9w0CCQUAMB0GCWCGSAFlAwQBKgQQHMqECNHY/vRVtykxKdw8YwSCBNCPknbRHW5QbQ/XnZIFFd7vyxvB37ITxp5MKiXRImcDJWSooT7+Mx+9GsyWvcmbNaEkb6NWzCsrqAzhAt5mjo+qYHRmSqTTHuFK//ROXF9tclnFlF/QzW/zb4RA89ESGky5GiN9ZDDbRsy2fabjNoMieRhhwK3RsjrwNPK6FjsS02ceEtksmmIZiQv6ZeZbNiRVAO2jNvaT2mIgADHekcNy9p/QrA+Z1NVQrlZO2f0W5doKq4FSNlW/vgytiFlermZyeSt24iR4QOrtU+WAr9Ar1HOlTSNUOJ8wQgy7kV5En8ObGTLmusWlF5759RIS356yB69z2ifRKlarH03810WnaQQI7+JV8ARYmh/TMfH8hDGAQyobpAwR+kB3SNCUIo89K/dZ8XkZ9UgrONXDj5exi4Wbc1RrtpC/XzKG68tHVWOhyfxFg4JeTw5I1RE1qUZ5xjA/YRfPNyiWyEZDw4Mku1o8MiPD3yG3UnORzNixwQpnu+u4QHo2kbIOpjR/5WCKmyrYaUQG4UiNBhoEgeb7+4f+cNNFttXMQVZ81tNITVxD14nJotGNN5p+Er+ps1u4VMGfLNvW+hGQYeE/E0rnrlXua/Uml1mP4FQp2yKTdNE4f5dRZY4GQAvcKHk9nKQr2vzW6tVCHFvxYoi9AS2CWo+rZ3SwriPQgkk+EEp+JRyw12sDCRk5vzuH8CtHQ30OfklR37HLGuLYtioDhxBpOciwQAeKDPawtf7ESR3MEFH/aAmpuLmfpAaEVEQoMB20NXv61m2s+IGM66dreYRpeYBBXpTIGzPMaB2wQEuaMqree+dH1g1ARPjFeuGq7nsUFG3XLsi0qh+/uGHo4b88nCYwTjjiJcD7x0io61DJRnb7sePMYTUtso4toFXpv5AO1cmiYgLtDzPKeXGmOsozszcFaQdaYKcOpoi6FoN18O/t/dxguDqpUMdG5M2RILqC1lUrWlkIGxji/2L7eQ55UWXW0J1nzFmIS/meKzIsNAjnFEvC0/289u4ub48OsyeuPc8FZI0bJ6xiKhRo8kbjxdTtwKuwUlrfaSkCRxoeD9Mj/YmRm7jZF6W08w5pW6OqYliM7UEXqPk73Z8jYYEYnuKmvqP/nF/dncI+GWbSHO/X7BlOXP/994pfpf/Duufsb6OGk94Up0TM8ugBs75AmYfQy83Ib+sdJ+tpLp3KEgp4DXLJFS1yNzyA9TcwTOYCkZ7aFtsrxJGfOoINrOhERquTUVbD+gcIrvC6cvE3j7X1qMckDg0PhYHrPAY6LHR44vN+5pRDZxcpuSHILw1YQnr7Dw9mKsSGtsacY4Z/yytnb3M0znpS2lDUeXsQ3ZgZeRrTkhncv6KbPF1RDbJz8PfcoreMzYS05SecrhgXG1/D8WyY7J4Zxyf3UA4RNkaoEKbvxwmUYwZgAOJ3mWJGmtMyfxYYuM7+aZ3g7WGG2zbgeFYOHqBBE8cVpcff1SlIigh0pAxKvfKvcOagbS18kwEJzozm4A+5Lt0rwSUEg2MrSegV0wW3tWcrNj9BxW8fWzJE4d/kYAaMKFMTg4h/+XEm7ufLcMbctC95FRhZS4zCbNzFQZfQDIEZKWX81a77fVBLWVkcgqJTBL1nDSo78cuhtzKplhEhhpfPooSgFTFCMB0GCSqGSIb3DQEJFDEQHg4AagB3AHQAXwBrAGUAeTAhBgkqhkiG9w0BCRUxFAQSVGltZSAxNjU3NzU4ODQ0MDE3MIIEQQYJKoZIhvcNAQcGoIIEMjCCBC4CAQAwggQnBgkqhkiG9w0BBwEwZgYJKoZIhvcNAQUNMFkwOAYJKoZIhvcNAQUMMCsEFNcZu8qLoK0WutssRbq6tiFIyyoRAgInEAIBIDAMBggqhkiG9w0CCQUAMB0GCWCGSAFlAwQBKgQQtqmbMDSWFvFB2f6BsJkiZICCA7ABhIrlnmoiNRWoY7EOgW3/aguTRLw5vCej2uTZ9hsXRe9WfvTCiVBnacLxOKGxm81mRpPwJ6uz0RVJW80btv8RSVWg5mqIXlvmQF4SvhOtGJTuQclnQoYdOc8jUM7b/3YNTR1HW9AjlIEbpvjPHsxzva0YxaDaPs23QQHFPZrCxG0fixnAv5gHkDS7JlgRtnouL4WCmQVz/QNtLNOUPCL3v3P/c/Shw1U66IcIDlRowmi9A2N1Eis+rkl+QdopCrb9bqNhjomGUIslgrPMB5AmZriXo53Wl8KtneZd11hZwV0PH9+Rio0aMT0DWgsIuWgTDtAsOqAn01xSqltA2DLGRFzki+T0RF96V1NZ3NNJUjfVYITcvulrxGwN7FFchOYfr0NhOKKijGECnWhzRMOF9DUBGjzbuALs/fKH+Q9tbD7A2NRcMd3hqUNcV1gmbgdGxSZMbSmL36Z0GOijNacwEaAYvPWXCmll/GMwIkb1p85Z6nDEuqMmQ2zHDiC8fxRGajPY38SyAq2lS1YQo6rFRLckUchhQnXUEMIz8K+3rzyfyQwk0jnR3qVBhoTrYX31wijpWyAPZPVniLSwPAU18ILbPxopWzdqWomxf43Pv5Y9iovI/ciVNiHEIj0343f/7NYuPMJ1Rh9zX2Hfzn67PdtKpxfg9wXlj1YxyAp1VQQfhxayoe+4IiWRS+AcWjo+t1MizUyDOqYLI8x15sV4wy4aSRUzcARhDiKgHXzoMgrfXKNEGw6KQJ7Xww3ECeZl1veM0NGKS1Cp2DLJmAoa9No1cQCWciYvAS60ObovAsTUzoWOcvnTsCz+DslZqI2nXw8CAshq9QJGqD2p4An35eNCS0MHU3wK8qXWZUwtll3nE3C608zDZ8Kw7WKCg6VK56vN84RhZ4X8cVYcthq+E0P0R8CrNCw6OSjTxtl+cDM+KviFLbFSE8peaHLFTbu2NqLGO/7QfqJ/JcEpT/JMM1dn6Wrrcrzw4xxQaJal/CBtNq1Y3JHhjEnJI/qMFY0mW59ff0dU2KxFTlPTTYurTx5cSaQlS0PXTsyy1FVDppoC02sHPqNjIhgoay0ycUFLOPBtue6KbxTgFFGBmax4xlGRJsV26MeETqMcu/xBHxPQxPEfRXS7rLuL9t8J4jMEVLrGszDjgIl0kONMGvox/ZMoQhnyPhtI+bPLbiqK0HIZKd29egNI5h/BYFNL00rMeTbK7AqhB7KtpFazqDhkamP+G4F5psDL9pkNWc1c6TBNMDEwDQYJYIZIAWUDBAIBBQAEIGj9qHLM6pLagsvnWwY8nS+GpJibJ4RxLhyvjYkOrTHqBBSc1U0P4YdaS1E0Mo62HzMXubYrewICJxA=
  keyname: and0X2tleQ==
  keypass: YWUzZDMwODYtNTQwYy00ZTBiLTlkNTUtMmE0MWM0ZDZhYTE0
  storepass: YWUzZDMwODYtNTQwYy00ZTBiLTlkNTUtMmE0MWM0ZDZhYTE0
kind: Secret
metadata:
  name: dev-jwt-jks-secret
  namespace: devops
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: devops
  name: devops-volume-deployment-secret
  labels:
    app.kubernetes.io/name: devops-volume
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: devops-volume-pod
  template:
    metadata:
      labels:
        app.kubernetes.io/name: devops-volume-pod
        app.kubernetes.io/version: 1.0.0
    spec:
      containers:
      - name: devops-blue
        image: timpamungkas/devops-blue:1.0.1
        resources:
          limits:
            cpu: "0.5"
            memory: 500M
        ports:
        - name:  http
          containerPort: 8111
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /devops/blue/actuator/health/readiness
            port: 8111
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 4
        livenessProbe:
          httpGet:
            path: /devops/blue/actuator/health/liveness
            port: 8111
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 4
        volumeMounts:
          - name: jwt-secret
            mountPath: "/secret/jwt"
            readOnly: true
        env:
        - name: JWT_JKS_FILE_PATH
          value: /secret/jwt/jwt.jks
        - name: JWT_JKS_FILE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dev-jwt-jks-secret
              key: storepass
        - name: JWT_JKS_KEY_NAME
          valueFrom:
            secretKeyRef:
              name: dev-jwt-jks-secret
              key: keyname
        - name: JWT_JKS_KEY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dev-jwt-jks-secret
              key: keypass        
      volumes:
        - name: jwt-secret
          secret:
            secretName: dev-jwt-jks-secret
  replicas: 1

---

apiVersion: v1
kind: Service
metadata:
  namespace: devops
  name: devops-blue-clusterip
  labels:
    app.kubernetes.io/name: devops-blue
spec:
  selector:
    app.kubernetes.io/name: devops-blue
  ports:
  - port: 8111
    name: http

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: devops
  name: ingress-devops-blue
  labels:
    app.kubernetes.io/name: devops-blue
spec:
  ingressClassName: nginx
  rules:
  - host: api.devops.local
    http:
      paths:
      - path: /devops/blue
        pathType: Prefix
        backend:
          service:
            name: devops-blue-clusterip
            port:
              number: 8111