configs:
  secret:
    # initial password : "password" (BCRYPT hash)
    argocdServerAdminPassword: $2a$12$n4pjYaCeLFGvZcUhQ3.TYOm2cwUhFXxcAeXTBFdhxtsTKhRMMFfcq

server:
  extraArgs:
    - --insecure
  ingress:
    enabled: "true"
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    hosts:
    - argocd.local
    paths:
    - /
  resources:
    requests:
      cpu: "0.2"
      memory: 200Mi
    limits:
      cpu: "0.5"
      memory: 500Mi
