apiVersion: v1
kind: Namespace
metadata:
  name:  devops

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: devops
  name: node-selector-deployment-blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-selector-blue
  template:
    metadata:
      labels:
        app: node-selector-blue
        version: 1.0.0
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: pool-high-mem
      containers:
      - name: devops-blue
        image: timpamungkas/devops-blue:1.0.0
        resources:
          requests:
            cpu: "0.02"
            memory: 32Mi
          limits:
            cpu: "0.3"
            memory: 384Mi
        ports:
        - name:  http
          containerPort: 8111
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /devops/blue/actuator/health/readiness
            port: 8111
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /devops/blue/actuator/health/liveness
            port: 8111
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 5
        env:
          - name: DEVOPS_YELLOW_URL
            value: http://devops-yellow-clusterip.devops-yellow:8112/devops/yellow
          - name: DEVOPS_WHITE_URL
            value: http://devops-white-clusterip.devops-white:8113/devops/white
