apiVersion: v1
kind: Namespace
metadata:
  name:  devops

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: devops
  name: devops-health-check-deployment
  labels:
    app.kubernetes.io/name: devops-health-check
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: devops-health-check
  template:
    metadata:
      labels:
        app.kubernetes.io/name: devops-health-check
        app.kubernetes.io/version: 1.0.0
    spec:
      containers:
      - name: devops-blue
        image: timpamungkas/devops-blue:1.0.0
        resources:
          limits:
            cpu: "0.5"
            memory: 500M
        ports:
        - name:  http
          containerPort: 8111
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /devops/blue/actuator/health/readiness
            port: 8111
            scheme: HTTP
          initialDelaySeconds: 60 #will wait for 60 seconds before it start probing
          periodSeconds: 30 #will periodically hit the http endpoint every 30 seconds
          timeoutSeconds: 5 #response time is 5 sec, if not 2xx within 5 sec, unhealthy
          failureThreshold: 4  #will take 4 consecutive bad response to consider the pod as unhealthy.
        livenessProbe:
          httpGet:
            path: /devops/blue/actuator/health/liveness
            port: 8111
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 4
  replicas: 3

---

apiVersion: v1
kind: Service
metadata:
  namespace: devops
  name: devops-health-check-service
  labels:
    app.kubernetes.io/name: devops-health-check
spec:
  selector:
    app.kubernetes.io/name: devops-health-check
  type:  LoadBalancer
  ports:
  - port: 9011         # port number to be available at host
    targetPort: 8111   # port on pod