env:
  open:
    STORAGE: local #will use local storage, enable chartmuseum API
    DISABLE_API: false
    CONTEXT_PATH: chartmuseum
  existingSecret: chartmuseum-credential
  existingSecretMappings: #securing the chartmuseum using username and password
    BASIC_AUTH_USER: chartmuseum-username
    BASIC_AUTH_PASS: chartmuseum-password

persistence: #local storage will be persisted using this configuration
  enabled: true
  accessMode: ReadWriteOnce
  size: 100Mi

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

ingress: #will enable ingress, using nginx with chartmuseum as path.
  enabled: "true"
  ingressClassName: nginx
  pathType: Prefix
  hosts:
  - name: chartmuseum.local
    path: /chartmuseum
