apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: devops-secret-blue
  namespace: devops
spec:
  encryptedData:
    devops-blue-html-text-one: AgBGUkMw39uckT0wTtWc2FJmAV3KLhUkSeW27kjEtI+3I4XwGueueg5ECrFLAy5qWsMSydf+/5tXxL5ut9X0Vyffr22IHEoIU9Kpce39oxHashss8UJ8pCdOANHaP9NWDXHyCeybqrohwanZWnFdO/drCHdwMaSlsMmiafclWGwUAlvdIkgJbsjPpHz4Z6fxD9Lg7zIE/wWqZUZH55D/rr3Nf5sate0FpvZNtB9MP3ImvMsNPG1UWPP4vY7XnS5PXp32ESO1g5dn7nKZ1S/3FCx67ynsHP+ESnT4oQxx4k08Px67KWXD8VooGviR4oBV7L4AQLV0yhG8u8/58DjMw+0L14GYDBe+g72AelFoM6MGwEYQ+LdHxOOnnFfBfE3S+cJyqK6jNJT5qSRtnTzOSdtvzy1eUFbvUqycXTwqchpWAsfYjnBMxOmXeMadTdpFbvHA3ncXEqdnSJVsRJxlggwhWeRF60L0CjIpu7UxhX2RvoLnzTvjZtuiQVgpFRNIJqEigaoDwZF40EvalOIc67vgyw6nkI9QVIRrrsejVnnr3DZT3CZqQxne3KK31NQfGQGCisCNeBBQdXw3OD1rZv/LhfLNf51VlBDYtX/RezBrhftnoYVh1FP0zNqvrXZvTMeDhceCt7mt4NXp8/P+weiz4quKkF5sGnT6VSZ3Tha06nnuzbX1XRqgGmUHtGVaMuu9bhF3li9C2K/UvBZ/To1qppHaNl+ldr+pP9PQzQ==
    devops-blue-html-text-two: AgCq5LiRUxHvjCLtMHgCJlv8W7/RwLMPWjHJArocSsPK9WjHE0bXRA65t8x6uAVvVGVxG/d/KsWOAnumrUvILT4BdPp88yqT60JpcITkOe9FUgo3fDC8e4J+fkGL6g2hIQ/sbfPJyXmXjNI1So9O15V6B4uiLzLs/EDdUWDpdcRTZff4QYxVjdDZf/lBBRKw04REXKuhO2YyXyy112pau9TD6Aw+ZfFuju2sQymNqe1A+yE48z1Sjc3/QYvUFSDfga5D/MhjjeZcPOvE+Pyapxtc4gIQWoZMnM7tfsMThhLHdKfjNts0rKklv3omYF4Ps8Ub/fJSDMs1hwwYTfsq7NuamEeE9JKl/3e8xOA9H9PP3wCMscFKHN44ZuF/cgmNcnvdAxQVWCH8AK+u1Jb3fOTHr7nmRjonlnL/J4O9wfD9y79N5o2Y1WOPlmcioRH1rtMM3cy+0GxXoLb14oJ/s5OzU/k19kZPen3pTq2486nTvddm/U1kBOZh9T8jWYhpOYKr95nevWkWqjdmezhpTTfFl2agJ/gfVLo3J2MIIcFHTbdTIw3E+d44MWEfO12dC4+020OLUpgB+1qvysWjHVqGA4ECy0mBKRuXu1SyVzDBuAt1W3iU3t0xUsePLi3DDXDi4z48WTPPSLMnTmwICDjvmYQr5RLueuDHPg1ON3kiISdX4/vysEL8uO212S9Rc/8lCpGhRdqEfyBxJZsnPmT3lD56PvsdbcCxKb8weFPWWh2sAsDMzQjKPQPZXU6BvPrSGrc=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: devops-secret-blue
      namespace: devops

