apiVersion: v1
kind: Namespace
metadata:
  name:  devops

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: devops
  name: devops-sealed-secret-deployment
  labels:
    app.kubernetes.io/name: devops-sealed-secret
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: devops-sealed-secret-pod
  template:
    metadata:
      labels:
        app.kubernetes.io/name: devops-sealed-secret-pod
        app.kubernetes.io/version: 1.0.0
    spec:
      containers:
      - name: devops-blue
        image: timpamungkas/devops-blue:1.0.0
        resources:
          limits:
            cpu: "0.5"
            memory: 500M
        ports:
        - name:  http
          containerPort: 8111
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /devops/blue/actuator/health/readiness
            port: 8111
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 4
        livenessProbe:
          httpGet:
            path: /devops/blue/actuator/health/liveness
            port: 8111
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 4
        env:
          - name: DEVOPS_BLUE_CONFIG_FILE
            valueFrom:
              secretKeyRef:
                name: my-secret                 # secret name to be used (since apply-ing sealed secret will generate k8s secret)
                key: my-config-file.yml         # secret key (filename, since we create sealed secret from file)
  replicas: 1

---

apiVersion: v1
kind: Service
metadata:
  namespace: devops
  name: devops-sealed-secret-service
  labels:
    app.kubernetes.io/name: devops-sealed-secret
spec:
  selector:
    app.kubernetes.io/name: devops-sealed-secret-pod
  type:  LoadBalancer
  ports:
  - port: 9011         # port number to be available at host
    targetPort: 8111   # port on pod