#Configuration value as described in bitnami helm documentation
replicaCount: 2

auth:
  username: admin
  existingPasswordSecret: devops-rabbitmq-secret #exisiting secrets we have created, the password is string "password"
  existingErlangSecret: devops-rabbitmq-secret  

resources:
  requests:
    cpu: "0.5"
    memory: 200Mi
  limits:
    cpu: "1"
    memory: 1Gi

ingress:
  enabled: true
  ingressClassName: nginx
  hostname: rabbitmq.local
  path: /rabbitmq

extraConfiguration: |- #as defined above
  management.path_prefix = /rabbitmq 

persistence:
  size: 1Gi
  