apiVersion: v1
kind: Namespace
metadata:
  name:  devops

---

kind: ConfigMap 
apiVersion: v1 
metadata:
  namespace: devops
  name: devops-blue-configmap
immutable: false
data:
  html.color.background: "#ff0000"
  html.color.text: "#eaf27c"
  html.text.one: "I just changed this text"
  html.text.two: "I also just changed this text"
  html.text.three: "This is the THIRD text from k8s configmap"