apiVersion: v1
kind: Secret
metadata:
  name: devops-blue-secret
  namespace: devops
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
data:
  html.text.four: VGhpcyBpcyBhIE5FVyBzZWNyZXQ=
  html.text.five: QW5vdGhlciBORVcgc2VjcmV0
  html.text.six: QW5kIG9uZSBtb3JlIE5FVyBzZWNyZXQ=