apiVersion: v1
kind: Namespace
metadata:
  name:  devops
  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: devops
  name: devops-reloader-deployment-blue
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: devops-reloader-blue
  template:
    metadata:
      labels:
        app.kubernetes.io/name: devops-reloader-blue
      annotations:
        # For other configuration, see https://github.com/stakater/Reloader
        reloader.stakater.com/auto: "true"
    spec:
      containers:
      - name: devops-blue
        image: timpamungkas/devops-blue:1.0.0
        resources:
          requests:
            cpu: "0.02"
            memory: 32Mi
          limits:
            cpu: "0.3"
            memory: 384Mi
        ports:
        - name:  http
          containerPort: 8111
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /devops/blue/actuator/health/readiness
            port: 8111
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /devops/blue/actuator/health/liveness
            port: 8111
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 5
        env:
          - name: DEVOPS_BLUE_HTML_BG_COLOR
            valueFrom:
              configMapKeyRef:
                name: devops-blue-configmap
                key: html.color.background
          - name: DEVOPS_BLUE_HTML_TEXT_COLOR
            valueFrom:
              configMapKeyRef:
                name: devops-blue-configmap
                key: html.color.text
          - name: DEVOPS_BLUE_HTML_TEXT_ONE
            valueFrom:
              configMapKeyRef:
                name: devops-blue-configmap
                key: html.text.one
          - name: DEVOPS_BLUE_HTML_TEXT_TWO
            valueFrom:
              configMapKeyRef:
                name: devops-blue-configmap
                key: html.text.two
          - name: DEVOPS_BLUE_HTML_TEXT_THREE
            valueFrom:
              configMapKeyRef:
                name: devops-blue-configmap
                key: html.text.three
          - name: DEVOPS_BLUE_HTML_TEXT_FOUR
            valueFrom:
              secretKeyRef:
                name: devops-blue-secret
                key: html.text.four
          - name: DEVOPS_BLUE_HTML_TEXT_FIVE
            valueFrom:
              secretKeyRef:
                name: devops-blue-secret
                key: html.text.five
          - name: DEVOPS_BLUE_HTML_TEXT_SIX
            valueFrom:
              secretKeyRef:
                name: devops-blue-secret
                key: html.text.six
  replicas: 1

---

apiVersion: v1
kind: Service
metadata:
  namespace: devops
  name: devops-blue-clusterip
  labels:
    app.kubernetes.io/name: devops-reloader-blue
spec:
  selector:
    app.kubernetes.io/name: devops-reloader-blue
  ports:
  - port: 8111
    name: http

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: devops
  name: ingress-devops-reloader-nginx-blue
  labels:
    app.kubernetes.io/name: ingress-devops-reloader-nginx-blue
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /devops/blue
        pathType: Prefix
        backend:
          service:
            name: devops-blue-clusterip
            port:
              number: 8111
