# https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/

apiVersion: v1
kind: ConfigMap
metadata:
  name: my-ingress-nginx-controller       # must be the same with LoadBalancer name (kubectl get service -n ingress-nginx)
  namespace: ingress-nginx
data: #is used to configure nginx.
  proxy-set-headers: ingress-nginx/nginx-custom-request-headers   # A on ingress-combination-nginx-configmap-headers.yml. will add request headers
  add-headers: ingress-nginx/nginx-custom-response-headers        # B pn ingress-combination-nginx-configmap-headers.yml. Added for custom response headers