apiVersion: v1
kind: Namespace
metadata:
  name:  devops

---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: devops-namespace-quota
  namespace: devops #Resource quota for NS devops. 
spec:
  hard:
    limits.cpu: "2"
    limits.memory: 8Gi
    configmaps: "4" #maximum 4 configmaps for this NS