apiVersion: v1
kind: Pod
metadata:
  name: devops-blue-pod
  namespace: devops
  labels:
    app.kubernetes.io/name: devops-blue
    app.kubernetes.io/version: 1.0.0
spec:
  containers:
  - name: devops-blue
    image: timpamungkas/devops-blue:1.0.0
    resources:
      requests:
        cpu : "0.5"
        memory: 500Mi
      limits:
        cpu : "0.5"
        memory: 1Gi
    ports:
    - name:  http
      containerPort: 8111
      protocol: TCP
    readinessProbe:
      httpGet:
        path: /devops/blue/actuator/health/readiness
        port: 8111
        scheme: HTTP
      initialDelaySeconds: 60
      periodSeconds: 30
      timeoutSeconds: 5
      failureThreshold: 4
    livenessProbe:
      httpGet:
        path: /devops/blue/actuator/health/liveness
        port: 8111
        scheme: HTTP
      initialDelaySeconds: 60
      periodSeconds: 30
      timeoutSeconds: 5
      failureThreshold: 4