apiVersion: v1
kind: Namespace
metadata:
  name:  devops

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: devops
  name: devops-port-forward-deployment
  labels:
    app.kubernetes.io/name: devops-port-forward
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: devops-port-forward
  template:
    metadata:
      labels:
        app.kubernetes.io/name: devops-port-forward
        app.kubernetes.io/version: 1.0.0
    spec:
      containers:
      - name: devops-blue
        image: timpamungkas/devops-blue:1.0.0
        resources:
          limits:
            cpu: "0.5"
            memory: 500M
        ports:
        - name:  http
          containerPort: 8111
          protocol: TCP
  replicas: 3
