# -------------------------------------------------------
# For deployment
image:
  repository: timpamungkas/devops-yellow
  tag: 1.0.0

applicationPort: 8112

actuatorPort: 8112

prometheusPath: /devops/yellow/actuator/prometheus

health:
  liveness:
    port: 8112
    path: /devops/yellow/actuator/health/liveness
  readiness:
    port: 8112
    path: /devops/yellow/actuator/health/readiness

# Mind the | which indicates this is raw string
extraVolumeMounts: |
  - name: upload-image-empty-dir
    mountPath: /upload/image
  - name: upload-doc-empty-dir
    mountPath: /upload/doc

# Mind the | which indicates this is raw string
extraVolumes: |
  - name: upload-image-empty-dir
    emptyDir: {}
  - name: upload-doc-empty-dir
    emptyDir: {}

# -------------------------------------------------------
# For service
service:
  type: ClusterIP
  port: 80

# -------------------------------------------------------
# For autoscaling
autoscaling:
  enabled: "true"
  minReplicas: 2
  maxReplicas: 4

# -------------------------------------------------------
# For ingress
ingress:
  enabled: "true"
  ingressClassName: nginx
  annotations: 
    nginx.ingress.kubernetes.io/limit-rpm: "30"
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "1"
  hosts:
  - host: api.devops.local
    paths:
    - path: /devops/yellow
      pathType: Prefix